import React, {useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Image,Linking,Platform,Pressable,ScrollView,Share,Switch,Text,TextInput,View,useWindowDimensions,AppState,BackHandler} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {StatusBar} from 'expo-status-bar';
import {LinearGradient} from 'expo-linear-gradient';
import {useAudioPlayer} from 'expo-audio';
import Ionicons from '@expo/vector-icons/Ionicons';
import data from './src/content/questions.json';
import appConfig from './app.json';
import {advance,careerTotals,correctAnswer,needsMoreSpecificAnswer,Difficulty,hydrate,initialProfile,makeSession,mastery,Mode,Profile,Question,Session,shuffled,submit,TIMER_SECONDS} from './src/core/quiz';
import {readProfile,writeProfile} from './src/services/storage';
import {buy,loadShop,restore,Shop,observeOwnership,refreshOwnership} from './src/services/billing';
import {Button,C,Icon,Kicker,s} from './src/ui';
import {t} from './src/i18n';
import {useUtcDay,utcDay} from './src/useUtcDay';
import {dailyResult} from './src/core/daily';
import {ArtworkCredits,GoalCelebration,VisualHome,VisualQuestion} from './src/VisualExperience';
import {ClubConnections} from './src/ClubConnections';
import {LetterBoard} from './src/LetterBoard';
import {CollectionProgress} from './src/CollectionProgress';
import {SquadArchive,SquadClue} from './src/SquadArchive';
import {PlayerAlbum,PlayerChapter,chapterQuestions} from './src/PlayerAlbum';
import {MistakeReview} from './src/MistakeReview';
const bank=data as Question[];
const modes:{id:Mode;name:string;sub:string;icon:keyof typeof Ionicons.glyphMap;tint:string}[]=[
{id:'world',name:t('modes_world_name'),sub:t('modes_world_sub'),icon:'earth-outline',tint:'#E1EBF2'},
{id:'players',name:t('modes_players_name'),sub:t('modes_players_sub'),icon:'shirt-outline',tint:'#F1E8DB'},
{id:'clubs',name:t('modes_clubs_name'),sub:t('modes_clubs_sub'),icon:'shield-outline',tint:'#E6EBD5'},
{id:'rules',name:t('modes_rules_name'),sub:t('modes_rules_sub'),icon:'flag-outline',tint:'#EDE5F1'},
{id:'legends',name:t('modes_legends_name'),sub:t('modes_legends_sub'),icon:'trophy-outline',tint:'#F2E5C5'},
{id:'portraits',name:'Player gallery',sub:'Recognise the face. Find the name.',icon:'person-outline',tint:'#E1EBF2'},
{id:'badges',name:'Guess the badge',sub:'Reimagined crests, real clubs.',icon:'shield-outline',tint:'#E6EBD5'},
{id:'squads',name:'World Cup squads',sub:'Explore the 2026 squad archive by country.',icon:'globe-outline',tint:'#E2EAE4'},
{id:'connections',name:'Club connections',sub:'Different shirts. Same player.',icon:'git-branch-outline',tint:'#E5ECE6'},
{id:'stadiums',name:'Stadium tour',sub:'Iconic grounds around the world.',icon:'business-outline',tint:'#DDE9EE'}];
type Tab='play'|'explore'|'learn'|'settings';
type Screen='tabs'|'quiz'|'result'|'shop'|'gate'|'privacy'|'replay'|'credits'|'squads'|'album';
export default function App(){return <SafeAreaProvider><Leoqo/></SafeAreaProvider>;}
function Leoqo(){
const {width}=useWindowDimensions(),wide=width>=800;
const [profile,setProfile]=useState<Profile>(initialProfile),profileRef=useRef(profile),saving=useRef(false);
const [ready,setReady]=useState(false),[fatal,setFatal]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
const [tab,setTab]=useState<Tab>('play'),[screen,setScreen]=useState<Screen>('tabs');
const [viewedResult,setViewedResult]=useState<Session|null>(null);
const [pendingRound,setPendingRound]=useState<Session|null>(null);
const [letters,setLetters]=useState(true);
const [answerHelp,setAnswerHelp]=useState('');
const [hint,setHint]=useState(false),[typed,setTyped]=useState(false),[input,setInput]=useState(''),[reporting,setReporting]=useState(false);
const [shop,setShop]=useState<Shop|null>(null),[adult,setAdult]=useState(false),[gateInput,setGateInput]=useState(''),[adultChecked,setAdultChecked]=useState(false),[gateCode,setGateCode]=useState('');
const gateAction=useRef<()=>void>(()=>{}),scroll=useRef<ScrollView>(null);
const session=screen==='result'&&viewedResult?viewedResult:profile.session,q=session?bank.find(q=>q.id===session.questionIds[session.index]):undefined,answer=session?.answers[session.index];
const textSize=profile.largeText?20:16,body=[s.body,{fontSize:textSize,lineHeight:textSize*1.5}];
const today=useUtcDay(),dailyDone=dailyResult(profile,today);
useEffect(()=>{if(Platform.OS!=='android')return;const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(busy)return true;if(screen==='tabs'&&tab==='play')return false;home();return true;});return()=>sub.remove();},[screen,tab,busy]);
useEffect(()=>{readProfile().then(raw=>{const p=hydrate(raw,bank);profileRef.current=p;setProfile(p);setReady(true);}).catch(()=>{setFatal(true);setNotice(t('notice_hydrate_failed'));setReady(true);});},[]);
useEffect(()=>{scroll.current?.scrollTo({y:0,animated:false});},[screen,tab,session?.index]);
useEffect(()=>observeOwnership(owned=>setShop(p=>({available:p?.available??false,product:p?.product??null,message:p?.message??'',owned}))),[]);
useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state==='active')void refreshOwnership();if(state!=='active'){setAdult(false);setAdultChecked(false);setGateInput('');}});return()=>sub.remove();},[]);
const [left,setLeft]=useState(TIMER_SECONDS),ticking=profile.timed&&screen==='quiz'&&!!session&&!answer;
useEffect(()=>{if(!ticking)return;setLeft(TIMER_SECONDS);const id=setInterval(()=>setLeft(l=>l-1),1000);return()=>clearInterval(id);},[ticking,session?.id,session?.index]);
useEffect(()=>{if(ticking&&left<=0)void choose('__timed_out__');},[left]);
const ding=useAudioPlayer(require('./assets/correct.wav')),buzz=useAudioPlayer(require('./assets/wrong.wav'));
// ponytail: also replays once when a saved round is reopened on an answered question; harmless, revisit if it annoys.
useEffect(()=>{if(!answer||!profile.sound)return;const p=answer.correct?ding:buzz;p.seekTo(0);p.play();},[answer]);
async function commit(next:Profile):Promise<boolean>{if(saving.current||fatal)return false;saving.current=true;setBusy(true);try{await writeProfile(JSON.stringify(next));profileRef.current=next;setProfile(next);return true;}catch{setNotice(t('notice_save_failed'));return false;}finally{saving.current=false;setBusy(false);}}
function home(t:Tab='play'){setTab(t);setScreen('tabs');setNotice('');}
function resetQuestion(){setAnswerHelp('');setLetters(true);setHint(false);setInput('');setTyped(false);setReporting(false);}
async function start(mode:Mode='mixed',options:{daily?:boolean;family?:boolean;revision?:string[];preview?:boolean;squadCode?:string;playerChapter?:PlayerChapter}={}){
if(mode==='squads'&&!options.squadCode){setScreen('squads');return;}
if(mode==='legends'&&!shop?.owned&&!options.preview){openShop();return;}
try{const seed=options.daily?`daily-${utcDay()}`:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const chapterIds=options.playerChapter?new Set(chapterQuestions(options.playerChapter).map(q=>q.id)):null;
const source=chapterIds?bank.filter(q=>chapterIds.has(q.id)):options.preview?bank.filter(q=>['legend-1956','legend-1967','legend-1979'].includes(q.id)):options.squadCode?bank.filter(q=>q.squadCode===options.squadCode):bank;
const next=makeSession(source,mode,profile.difficulty,profile.seen,seed,{...options,premium:!!shop?.owned||!!options.preview,revision:options.preview?source.map(q=>q.id):options.revision});
if(!options.daily&&!options.revision&&!options.preview&&next.questionIds.every(id=>profile.seen.includes(id))){setPendingRound(next);setScreen('replay');return;}
await beginRound(next);}catch(e){setNotice(e instanceof Error?e.message:t('notice_round_start_failed'));}}
async function beginRound(next:Session){if(await commit({...profileRef.current,session:next})){setPendingRound(null);setViewedResult(null);resetQuestion();setNotice('');setScreen('quiz');}}
async function choose(value:string){if(!q||answer)return;if(needsMoreSpecificAnswer(q,value)){setAnswerHelp(t('quiz_more_specific_name'));return;}setAnswerHelp('');await commit(submit(profileRef.current,bank,value,hint));}
async function next(){const p=advance(profileRef.current);if(await commit(p)){resetQuestion();if(p.session?.completed){setViewedResult(null);setScreen('result');}}}
async function report(reason:string){if(!q)return;const p=profileRef.current;if(await commit({...p,reports:[...p.reports,{questionId:q.id,reason,at:new Date().toISOString()}]})){setReporting(false);setNotice(t('notice_report_saved'));}}
function adultStep(action:()=>void){if(adult){action();return;}gateAction.current=action;setGateCode(String(100+Math.floor(Math.random()*900)));setGateInput('');setAdultChecked(false);setNotice('');setScreen('gate');}
async function refreshShop(){setScreen('shop');setBusy(true);setShop(await loadShop());setBusy(false);}
function openShop(){adultStep(()=>{void refreshShop();});}
async function purchase(){if(!shop?.product||!adult||busy)return;setBusy(true);setNotice('');try{const ok=await buy(shop.product);setShop(p=>({...p!,owned:ok}));setNotice(t('notice_pack_unlocked'));}catch(e:any){setNotice(e.userCancelled?t('notice_purchase_cancelled'):e.message??t('notice_purchase_store_error'));}finally{setBusy(false);}}
async function restorePurchase(){if(!adult||busy)return;setBusy(true);try{const unlocked=await restore();setShop(p=>({available:p?.available??false,product:p?.product??null,message:p?.message??'',owned:unlocked}));setNotice(unlocked?t('notice_restore_success'):t('notice_restore_none'));}catch(e:any){setNotice(e.message??t('notice_restore_unavailable'));}finally{setBusy(false);}}
async function shareText(text:string,title:string){try{if(Platform.OS==='web'){const file=new Blob([text],{type:'text/plain'}),url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=`${title}.txt`;a.click();URL.revokeObjectURL(url);setNotice(t('notice_share_downloaded'));}else await Share.share({message:text,title});}catch{setNotice(t('notice_share_unavailable'));}}
function difficultyPicker(){return <View style={s.levels}>{(['starter','fan','expert'] as Difficulty[]).map(level=><Pressable key={level} accessibilityRole="button" accessibilityLabel={`${t(`difficulty_${level}`)} difficulty`} accessibilityState={{selected:profile.difficulty===level}} onPress={()=>{void commit({...profileRef.current,difficulty:level});}} style={[s.level,profile.difficulty===level&&s.levelActive]}><Text style={[s.levelText,profile.difficulty===level&&{color:C.white}]}>{t(`difficulty_${level}`)}</Text></Pressable>)}</View>;}
function modeRow(mode:typeof modes[number]){const count=bank.filter(q=>q.category===mode.id).length;return <Pressable key={mode.id} accessibilityRole="button" accessibilityLabel={`${mode.name}, ${t('mode_count_questions',{count})}${mode.id==='legends'?t('mode_legends_suffix'):''}`} onPress={()=>{void start(mode.id);}} style={({pressed})=>[s.modeRow,pressed&&{backgroundColor:C.pale}]}><View style={[s.modeIcon,{backgroundColor:mode.tint}]}><Icon name={mode.icon} size={25}/></View><View style={{flex:1,gap:4}}><Text style={s.modeTitle}>{mode.name}</Text><Text style={[s.small,{fontSize:profile.largeText?17:14}]}>{mode.sub}</Text></View><Text style={s.count}>{count}</Text><Icon name={mode.id==='legends'&&!shop?.owned?'lock-closed-outline':'arrow-forward'} size={19}/></Pressable>;}
const stats=careerTotals(profile),accuracy=stats.answered?Math.round(stats.correct/stats.answered*100):0;
if(!ready)return <SafeAreaView style={s.root}><ActivityIndicator style={{marginTop:80}} color={C.green} accessibilityLabel="Opening your saved progress"/></SafeAreaView>;
return <SafeAreaView style={s.root}><StatusBar style="dark"/><View style={s.shell}>
<View style={s.header}><Pressable onPress={()=>home()} accessibilityRole="button" accessibilityLabel={t('home_leoqo_label')} style={s.brand}><Image source={require("./assets/brand/lion-ball.png")} accessible={false} style={{width:46,height:46,borderRadius:12}}/><Text style={s.wordmark}>leoqo<Text style={{color:C.green}}>.</Text></Text></Pressable>{width>=360&&<View style={s.guest}><View style={s.onlineDot}/><Text style={s.guestText}>{t('home_guest_text')}</Text></View>}</View>
<ScrollView ref={scroll} style={{flex:1}} contentContainerStyle={[s.content,wide&&{paddingHorizontal:36}]} keyboardShouldPersistTaps="handled">
{!fatal&&screen==='replay'&&pendingRound&&<View style={s.narrow}><Kicker>{t('replay_kicker')}</Kicker><Text style={s.h1}>{t('replay_title')}</Text><Text style={body}>{t('replay_body')}</Text><Button title={t('replay_start')} disabled={busy} onPress={()=>{void beginRound(pendingRound);}}/><Button secondary title={t('replay_explore')} onPress={()=>{setPendingRound(null);home('explore');}}/><Button secondary title={t('replay_back')} onPress={()=>{setPendingRound(null);home();}}/></View>}
{!!notice&&<View accessibilityLiveRegion="polite" style={s.notice}><Icon name="information-circle-outline" size={21}/><Text style={[body,{flex:1}]}>{notice}</Text><Pressable accessibilityRole="button" accessibilityLabel={t('notice_dismiss')} onPress={()=>setNotice('')} style={s.dismiss}><Icon name="close" size={20}/></Pressable></View>}
{fatal&&screen!=='gate'&&<View style={s.section}><Text style={s.h2}>{t('fatal_title')}</Text><Text style={body}>{t('fatal_body')}</Text><Button title={t('fatal_retry')} onPress={()=>{readProfile().then(raw=>{const p=hydrate(raw,bank);setProfile(p);profileRef.current=p;setFatal(false);setNotice('');}).catch(()=>setNotice(t('fatal_retry_failed')));}}/><Button secondary title={t('fatal_export')} onPress={()=>{readProfile().then(raw=>shareText(raw??t('fatal_no_save'),'leoqo-recovery')).catch(()=>setNotice(t('fatal_export_read_failed')));}}/><Button secondary title={t('fatal_reset')} onPress={()=>adultStep(()=>{writeProfile(JSON.stringify(initialProfile())).then(()=>{profileRef.current=initialProfile();setProfile(initialProfile());setFatal(false);home();}).catch(()=>setNotice(t('fatal_reset_failed')));})}/></View>}

{!fatal&&screen==='tabs'&&tab==='play'&&<>

{session&&!session.completed&&<Pressable accessibilityRole="button" onPress={()=>{resetQuestion();setScreen('quiz');}} style={s.resume}><Icon name="play-circle-outline"/><Text style={[s.modeTitle,{flex:1}]}>{t('home_resume')}</Text><Text style={s.small}>{session.answers.length}/{session.questionIds.length}</Text><Icon name="arrow-forward" size={18}/></Pressable>}
<VisualHome today={today} dailyDone={!!dailyDone} onDaily={()=>{if(dailyDone){setViewedResult(dailyDone);setScreen('result');}else void start('mixed',{daily:true});}} onAlbum={()=>setScreen('album')} profile={profile} onStart={mode=>{void start(mode);}} onCredits={()=>setScreen('credits')}/><Pressable accessibilityRole="button" accessibilityLabel="Explore World Cup squads" onPress={()=>setScreen('squads')} style={{backgroundColor:C.ink,padding:20,borderRadius:16,gap:8,marginBottom:20}}><Text style={{color:C.lime,fontSize:10,fontWeight:'800',letterSpacing:2}}>WORLD CUP ARCHIVE</Text><Text style={{color:'white',fontSize:24,fontWeight:'800'}}>48 squads. Know them all?</Text><Text style={{color:'#D8E4DF',fontSize:14}}>1,248 questions · Choose your country →</Text></Pressable><CollectionProgress compact bank={bank} profile={profile} onStart={mode=>{if(mode==='portraits')setScreen('album');else void start(mode);}}/><Button title={t('home_kickoff_label')} secondary icon="shuffle-outline" onPress={()=>{void start();}}/>
<View style={[s.columns,!wide&&{flexDirection:'column'}]}><View style={{flex:wide?1.5:undefined}}><View style={s.sectionHead}><Text style={s.h2}>{t('home_find_game_h2')}</Text><Pressable accessibilityRole="button" onPress={()=>home('explore')} style={s.textLink}><Text style={s.linkText}>{t('home_all_topics')}</Text><Icon name="arrow-forward" size={17}/></Pressable></View><Text style={[s.small,{marginBottom:12}]}>{t('home_choose_comfort')}</Text>{difficultyPicker()}<View style={s.modeList}>{modes.slice(0,4).map(modeRow)}</View></View><View style={{flex:wide?1:undefined,gap:18}}><Pressable accessibilityRole="button" onPress={()=>{void start('mixed',{family:true});}} style={s.family}><Icon name="people-outline" size={28}/><View style={{flex:1,gap:6}}><Text style={s.modeTitle}>{t('home_family_title')}</Text><Text style={s.small}>{t('home_family_sub')}</Text></View><Icon name="arrow-forward" size={19}/></Pressable></View></View><View style={s.footerNote}><Icon name="heart-outline" size={17}/><Text style={s.small}>{t('home_footer_note')}</Text></View>
</>}
{!fatal&&screen==='tabs'&&tab==='explore'&&<View style={s.section}><Kicker>{t('explore_kicker')}</Kicker><Text style={s.h1}>{t('explore_h1')}</Text><Text style={body}>{t('explore_body')}</Text>{difficultyPicker()}<View style={s.modeList}>{modes.map(modeRow)}</View><Text style={s.tiny}>{t('explore_footnote')}</Text></View>}
{!fatal&&screen==='tabs'&&tab==='learn'&&<View style={s.section}><Kicker>{t('learn_kicker')}</Kicker><Text style={s.h1}>{t('learn_h1')}</Text><View style={s.statRow}>{[[stats.rounds,t('learn_stat_rounds')],[`${accuracy}%`,t('learn_stat_accuracy')],[profile.seen.length,t('learn_stat_questions')]].map(([value,label])=><View key={label} style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.small}>{label}</Text></View>)}</View>{mastery(profile,bank).length>0&&<><Text style={s.h2}>{t('learn_mastery_h2')}</Text><Text style={s.small}>Based on your last {profile.history.length} completed rounds.</Text>{mastery(profile,bank).map(m=><View key={m.category} style={s.history}><View><Text style={s.modeTitle}>{modes.find(x=>x.id===m.category)?.name??m.category}</Text><Text style={s.small}>{t('learn_mastery_correct',{correct:m.correct,total:m.total})}</Text></View><Text style={s.scoreText}>{Math.round(m.correct/m.total*100)}%</Text></View>)}</>}<Text style={s.h2}>{t('learn_worth_h2')}</Text><Text style={body}>{profile.mistakes.length?t('learn_mistakes_body',{n:profile.mistakes.length}):t('learn_mistakes_empty')}</Text>{profile.mistakes.length>0&&<Button title={t('learn_practice_mistakes')} icon="refresh-outline" onPress={()=>{void start('mixed',{revision:profile.mistakes});}}/>}<MistakeReview items={bank.filter(q=>profile.mistakes.includes(q.id)&&(!q.premium||shop?.owned))} largeText={profile.largeText} onPractise={id=>{void start('mixed',{revision:[id]});}} onSource={url=>adultStep(()=>{home('learn');Linking.openURL(url).catch(()=>setNotice(t('notice_source_open_failed')));})}/><Text style={[s.h2,{marginTop:14}]}>{t('learn_recent_h2')}</Text>{profile.history.length===0?<Text style={body}>{stats.rounds===0?t('learn_recent_empty'):'No recent rounds are stored on this device.'}</Text>:[...profile.history].reverse().slice(0,8).map(h=><View key={h.id} style={s.history}><View><Text style={s.modeTitle}>{h.daily?t('learn_history_daily'):h.family?t('learn_history_family'):modes.find(m=>m.id===h.mode)?.name??t('learn_history_mixed')}</Text><Text style={s.small}>{t('learn_history_meta',{difficulty:t(`difficulty_${h.difficulty}`),n:h.questionIds.length})}</Text></View><Text style={s.scoreText}>{h.answers.filter(a=>a.correct).length}/{h.questionIds.length}</Text></View>)}</View>}
{!fatal&&screen==='tabs'&&tab==='settings'&&<View style={s.section}><Kicker>{t('settings_kicker')}</Kicker><Text style={s.h1}>{t('settings_h1')}</Text><View style={s.settingRow}><View style={{flex:1}}><Text style={s.modeTitle}>{t('settings_large_text_title')}</Text><Text style={s.small}>{t('settings_large_text_sub')}</Text></View><Switch accessibilityLabel={t('settings_large_text_label')} value={profile.largeText} onValueChange={largeText=>{void commit({...profileRef.current,largeText});}} trackColor={{true:C.green,false:C.line}}/></View><View style={s.settingRow}><View style={{flex:1}}><Text style={s.modeTitle}>{t('settings_timed_title')}</Text><Text style={s.small}>{t('settings_timed_sub',{s:TIMER_SECONDS})}</Text></View><Switch accessibilityLabel={t('settings_timed_label')} value={profile.timed} onValueChange={timed=>{void commit({...profileRef.current,timed});}} trackColor={{true:C.green,false:C.line}}/></View><View style={s.settingRow}><View style={{flex:1}}><Text style={s.modeTitle}>{t('settings_sound_title')}</Text><Text style={s.small}>{t('settings_sound_sub')}</Text></View><Switch accessibilityLabel={t('settings_sound_label')} value={profile.sound} onValueChange={sound=>{void commit({...profileRef.current,sound});}} trackColor={{true:C.green,false:C.line}}/></View><Text style={s.h2}>{t('settings_default_difficulty')}</Text>{difficultyPicker()}<View style={s.infoBox}><Icon name="cloud-offline-outline"/><View style={{flex:1,gap:8}}><Text style={s.modeTitle}>{t('settings_saved_device_title')}</Text><Text style={body}>{t('settings_saved_device_body')}</Text></View></View><Button secondary title={t('settings_export_progress')} icon="download-outline" onPress={()=>adultStep(()=>{home('settings');void shareText(JSON.stringify(profileRef.current,null,2),'leoqo-progress');})}/><Button secondary title={t('settings_export_reports',{n:profile.reports.length})} onPress={()=>adultStep(()=>{home('settings');void shareText(JSON.stringify(profileRef.current.reports,null,2),'leoqo-reports');})}/><Button secondary title={t('settings_purchases')} icon="bag-outline" onPress={openShop}/><Button secondary title={t('settings_privacy')} onPress={()=>setScreen('privacy')}/><Button secondary title="Artwork credits" onPress={()=>setScreen('credits')}/><Text style={s.tiny}>Visual edition · {appConfig.expo.version}</Text><Text style={s.tiny}>{t('settings_footer')}</Text></View>}

{!fatal&&screen==='quiz'&&session&&q&&<View style={[s.quizWrap,wide&&{maxWidth:750,alignSelf:'center',width:'100%'}]}><View style={s.sectionHead}><Pressable accessibilityRole="button" accessibilityLabel={t('quiz_save_leave_label')} onPress={()=>home()} style={s.back}><Icon name="arrow-back" size={20}/><Text style={s.linkText}>{t('quiz_save_leave')}</Text></Pressable><Text style={s.small}>{ticking?t('quiz_seconds_left',{s:Math.max(left,0)}):session.daily?t('quiz_daily'):session.family?t('quiz_family_turn',{n:session.index%2+1}):t('quiz_take_time')}</Text></View><View style={s.quizProgress}><View style={[s.quizProgressFill,{width:`${session.index/session.questionIds.length*100}%`}]}/></View><View style={[s.sectionHead,{marginTop:18}]}><Kicker>{t('quiz_progress',{n:session.index+1,total:session.questionIds.length})}</Kicker><Text style={s.small}>{t('quiz_correct_count',{n:session.answers.filter(a=>a.correct).length})}</Text></View><Text style={s.era}>{q.era}</Text>{q.squadClue&&<SquadClue {...q.squadClue}/>}{q.clubConnections&&<ClubConnections clubs={q.clubConnections} identity={q.id}/>}{q.visual&&<VisualQuestion question={q} answered={!!answer} correct={!!answer?.correct}/>}<Text accessibilityRole="header" style={[s.question,{fontSize:profile.largeText?30:wide?30:25}]}>{q.prompt}</Text>
{q.category==='portraits'&&letters&&!typed&&!answer?<View style={{gap:12}}><LetterBoard key={q.id} answer={q.answer} seed={session.seed+q.id} disabled={busy} onSubmit={value=>{void choose(value);}}/><Pressable accessibilityRole="button" accessibilityLabel="Use answer choices" onPress={()=>setLetters(false)} style={s.textLink}><Text style={s.linkText}>Use answer choices</Text></Pressable></View>:typed&&!answer?<View style={{gap:14}}><TextInput autoFocus accessibilityLabel={t('quiz_answer_label')} placeholder={t('quiz_answer_placeholder')} value={input} onChangeText={value=>{setInput(value);setAnswerHelp('');}} onSubmitEditing={()=>{if(input.trim())void choose(input);}} style={[s.input,{fontSize:textSize}]} autoCorrect={false} maxLength={100}/>{!!answerHelp&&<Text accessibilityLiveRegion="polite" style={body}>{answerHelp}</Text>}<Text style={s.small}>{t('quiz_name_help')}</Text><Button title={t('quiz_check_answer')} disabled={!input.trim()||busy} onPress={()=>{void choose(input);}}/></View>:<View style={{gap:12,flexDirection:q.visual?'row':'column',flexWrap:'wrap'}}>{shuffled(q.options,session.seed+q.id).map((option,i)=>{const isRight=!!answer&&correctAnswer(q,option),chosen=!!answer&&correctAnswer({...q,answer:option,aliases:[]},answer.value);return <Pressable key={option} disabled={!!answer||busy} accessibilityRole="button" accessibilityLabel={`${option}${isRight?t('quiz_option_correct_suffix'):''}`} accessibilityState={{disabled:!!answer||busy,selected:chosen}} onPress={()=>{void choose(option);}} style={({pressed})=>[s.option,q.visual&&{width:'48%',minHeight:64,padding:10,gap:8},pressed&&{backgroundColor:C.pale},isRight&&s.correct,chosen&&!answer?.correct&&s.incorrect]}><View style={[s.optionLetter,isRight&&{backgroundColor:C.green}]}>{isRight?<Icon name="checkmark" color="white" size={18}/>:<Text style={s.optionLetterText}>{String.fromCharCode(65+i)}</Text>}</View><Text style={[s.optionText,{fontSize:profile.largeText?22:q.visual?15:18},isRight&&{color:C.green}]}>{option}</Text>{chosen&&!answer?.correct&&<Icon name="close-circle-outline" color={C.red}/>}</Pressable>;})}</View>}
{!answer&&<View style={{gap:14,marginTop:18}}><View style={s.quizActions}><Pressable accessibilityRole="button" onPress={()=>setHint(true)} style={s.textLink}><Icon name="bulb-outline" size={19}/><Text style={s.linkText}>{t('quiz_hint')}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={t('quiz_skip_label')} onPress={()=>{void choose('__skipped__');}} style={s.textLink}><Text style={s.linkText}>{t('quiz_skip')}</Text><Icon name="play-skip-forward-outline" size={18}/></Pressable></View>{hint&&<Text accessibilityLiveRegion="polite" style={[body,s.hint]}>{q.hint}</Text>}{(q.category==='players'||q.category==='portraits')&&<Pressable accessibilityRole="button" onPress={()=>{setTyped(!typed);setAnswerHelp('');}} style={s.textLink}><Icon name="create-outline" size={18}/><Text style={s.linkText}>{typed?t('quiz_use_choices'):t('quiz_type_name')}</Text></Pressable>}</View>}
{!!answer&&<View accessibilityLiveRegion="polite" style={s.feedback}><View style={s.textLink}><Icon name={answer.correct?'checkmark-circle-outline':'book-outline'} color={C.green}/><Text style={[s.h2,{flex:1}]}>{answer.correct?t('quiz_feedback_correct'):answer.value==='__timed_out__'?t('quiz_feedback_timeout'):t('quiz_feedback_incorrect')}</Text></View><Text style={[s.modeTitle,{fontSize:22}]}>{q.answer}</Text><Text style={body}>{q.explanation}</Text><Pressable accessibilityRole="button" onPress={()=>adultStep(()=>{setScreen('quiz');Linking.openURL(q.source).catch(()=>setNotice(t('notice_source_open_failed')));})} style={s.textLink}><Text style={s.linkText}>{t('quiz_read_source')}</Text><Icon name="open-outline" size={17}/></Pressable><Button title={session.index===session.questionIds.length-1?t('quiz_see_result'):t('quiz_next')} disabled={busy} icon="arrow-forward" onPress={()=>{void next();}}/></View>}
<Pressable accessibilityRole="button" onPress={()=>setReporting(!reporting)} style={[s.textLink,{alignSelf:'center',marginTop:26}]}><Icon name="flag-outline" size={15}/><Text style={s.small}>{t('quiz_report_prompt')}</Text></Pressable>{reporting&&<View style={s.reportBox}><Text style={body}>{t('quiz_report_intro')}</Text>{[t('report_incorrect_fact'),t('report_unclear_wording'),t('report_answer_not_accepted')].map(reason=><Button key={reason} secondary title={reason} onPress={()=>{void report(reason);}}/>)}</View>}</View>}

{!fatal&&screen==='result'&&session&&<View style={s.result}><GoalCelebration perfect={session.answers.every(a=>a.correct)}/><Kicker>{t('result_kicker')}</Kicker><Text style={s.resultScore}>{session.answers.filter(a=>a.correct).length}<Text style={{fontSize:36,color:C.muted}}> / {session.questionIds.length}</Text></Text><Text style={[s.h1,{textAlign:'center'}]}>{session.answers.every(a=>a.correct)?t('result_perfect'):t('result_encourage')}</Text><Text style={[body,{textAlign:'center'}]}>{t('result_body')}</Text>{session.family&&<View style={s.statRow}>{[0,1].map(player=><View style={s.stat} key={player}><Text style={s.statValue}>{session.answers.filter((a,i)=>i%2===player&&a.correct).length}</Text><Text style={s.small}>{t('result_fan_label',{n:player+1})}</Text></View>)}</View>}<View style={{width:'100%',maxWidth:400,gap:12}}><Button title={t('result_play_again')} icon="arrow-forward" onPress={()=>{if(session.mode==='portraits')setScreen('album');else void start(session.mode,{family:session.family});}}/><Button secondary title={t('result_review')} onPress={()=>home('learn')}/><Button secondary title={t('result_share')} icon="share-outline" onPress={()=>adultStep(()=>{setScreen('result');void shareText(t('share_score_message',{score:session.answers.filter(a=>a.correct).length,total:session.questionIds.length,daily:session.daily?t('share_score_daily_suffix',{date:today}):''}),'leoqo-score');})}/><Pressable accessibilityRole="button" onPress={()=>home()} style={[s.textLink,{alignSelf:'center'}]}><Text style={s.linkText}>{t('result_back')}</Text></Pressable></View></View>}

{screen==='album'&&<PlayerAlbum solved={profile.solved??[]} onBack={()=>home()} onStart={playerChapter=>{void start('portraits',{playerChapter});}}/>}
{screen==='squads'&&<SquadArchive solved={profile.solved??[]} onBack={()=>home()} onStart={code=>{void start('squads',{squadCode:code});}}/>}
{screen==='gate'&&<View style={s.narrow}><Kicker>{t('gate_kicker')}</Kicker><Text style={s.h1}>{t('gate_h1')}</Text><Text style={body}>{t('gate_body')}</Text><Text style={body}>{t('gate_digits')}<Text style={{fontWeight:'800'}}>{gateCode}</Text></Text><TextInput accessibilityLabel={t('gate_digits_label')} keyboardType="number-pad" maxLength={3} value={gateInput} onChangeText={setGateInput} style={s.input}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:adultChecked}} onPress={()=>setAdultChecked(!adultChecked)} style={s.checkRow}><Icon name={adultChecked?'checkbox':'square-outline'}/><Text style={[body,{flex:1}]}>{t('gate_confirm_checkbox')}</Text></Pressable><Button title={t('gate_continue')} disabled={gateInput!==gateCode.split('').reverse().join('')||!adultChecked} onPress={()=>{setAdult(true);gateAction.current();}}/><Button secondary title={t('gate_back')} onPress={()=>home()}/></View>}
{!fatal&&screen==='shop'&&<View style={s.narrow}><Kicker>{t('shop_kicker')}</Kicker><View style={s.packArtwork}><Icon name="trophy-outline" color={C.ink} size={65}/><Text style={s.packYear}>1956 — 1995</Text></View><Text style={s.h1}>{t('shop_h1')}</Text><Text style={body}>{t('shop_body')}</Text><View style={s.packFeatures}>{[t('shop_feature_1'),t('shop_feature_2'),t('shop_feature_3')].map(f=><View key={f} style={s.textLink}><Icon name="checkmark" color={C.green} size={20}/><Text style={[body,{flex:1}]}>{f}</Text></View>)}</View>{busy&&<ActivityIndicator accessibilityLabel={t('shop_contacting_store')} color={C.green}/>}<Text style={s.price}>{shop?.owned?t('shop_owned_price'):shop?.product?.product.priceString??t('shop_coming_soon')}</Text>{!!shop?.message&&<Text style={body}>{shop.message}</Text>}{shop?.owned?<Button title={t('shop_play_owned')} onPress={()=>{void start('legends');}}/>:<Button title={shop?.available?t('shop_unlock',{price:shop.product!.product.priceString}):t('shop_unavailable')} disabled={!shop?.available||busy} onPress={()=>{if(!adult)adultStep(()=>{setScreen('shop');});else void purchase();}}/>}<Button secondary title={t('shop_try_free')} onPress={()=>{void start('legends',{preview:true});}}/><Button secondary title={t('shop_restore')} disabled={busy} onPress={()=>{if(!adult)adultStep(()=>{setScreen('shop');});else void restorePurchase();}}/><Pressable accessibilityRole="button" onPress={()=>home()} style={[s.textLink,{alignSelf:'center'}]}><Text style={s.linkText}>{t('shop_keep_free')}</Text></Pressable><Text style={s.tiny}>{t('shop_price_footnote')}</Text></View>}
{!fatal&&screen==='credits'&&<View style={s.section}><ArtworkCredits onOpen={url=>adultStep(()=>{setScreen('credits');Linking.openURL(url).catch(()=>setNotice(t('notice_source_open_failed')));})}/><Button secondary title='Back to the clubhouse' onPress={()=>home()}/></View>}
{!fatal&&screen==='privacy'&&<View style={s.section}><Kicker>{t('privacy_kicker')}</Kicker><Text style={s.h1}>{t('privacy_h1')}</Text><Text style={body}>{t('privacy_intro')}</Text><Text style={s.h2}>{t('privacy_section_privacy_h2')}</Text><Text style={body}>{t('privacy_privacy_body')}</Text><Text style={body}>{t('privacy_purchases_body')}</Text><Text style={s.h2}>{t('privacy_section_content_h2')}</Text><Text style={body}>{t('privacy_content_body')}</Text><Text style={s.h2}>{t('privacy_section_delete_h2')}</Text><Text style={body}>{t('privacy_delete_body')}</Text><Button secondary title={t('privacy_delete_button')} onPress={()=>adultStep(()=>{void commit(initialProfile()).then(ok=>{if(ok)home('settings');});})}/><Button secondary title={t('privacy_back_settings')} onPress={()=>home('settings')}/></View>}
{busy&&screen!=='shop'&&<Text accessibilityLiveRegion="polite" style={[s.tiny,{textAlign:'center',marginTop:12}]}>{t('saving_indicator')}</Text>}
</ScrollView>
{screen==='tabs'&&!fatal&&<View style={s.nav}>{([{id:'play',label:t('nav_play'),icon:'football-outline'},{id:'explore',label:t('nav_explore'),icon:'compass-outline'},{id:'learn',label:t('nav_learn'),icon:'book-outline'},{id:'settings',label:t('nav_settings'),icon:'options-outline'}] as const).map(item=><Pressable key={item.id} accessibilityRole="tab" accessibilityState={{selected:tab===item.id}} accessibilityLabel={item.label} onPress={()=>home(item.id)} style={[s.navItem,tab===item.id&&s.navActive]}><Icon name={item.icon} color={tab===item.id?C.green:C.muted} size={23}/><Text style={[s.navLabel,tab===item.id&&{color:C.green,fontWeight:'800'}]}>{item.label}</Text></Pressable>)}</View>}
</View></SafeAreaView>;
}
