import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const dir='.expo/redesign';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});
await page.goto('http://127.0.0.1:8081');
await page.getByRole('button',{name:'Guess the player, 86 photo questions',exact:true}).waitFor();
await page.screenshot({path:`${dir}/home.png`});
await page.getByRole('button',{name:'Explore Champions League 2026/27',exact:true}).click();
await page.screenshot({path:`${dir}/clubs.png`});
await page.getByRole('button',{name:/Aston Villa club/}).click();
await page.screenshot({path:`${dir}/quiz.png`});
await page.getByRole('button',{name:'Leoqo home',exact:true}).click();
await page.getByRole('button',{name:'Guess the player, 86 photo questions',exact:true}).click();
await page.getByTestId('letter-board').waitFor();
await page.screenshot({path:`${dir}/player.png`});
await page.getByRole('button',{name:'Leoqo home',exact:true}).click();
await page.getByRole('button',{name:/Lineup detective/}).click();
await page.getByRole('button',{name:'Lineup puzzle 1',exact:true}).click();
await page.screenshot({path:`${dir}/lineup.png`,fullPage:true});
await page.getByRole('button',{name:'Leoqo home',exact:true}).click();
await page.getByRole('button',{name:'Open player album',exact:true}).click();
await page.screenshot({path:`${dir}/album.png`});
await page.getByRole('button',{name:'Leoqo home',exact:true}).click();
await page.getByRole('tab',{name:'My learning',exact:true}).click();
await page.screenshot({path:`${dir}/learning.png`});
await page.getByRole('tab',{name:'Settings',exact:true}).click();
await page.screenshot({path:`${dir}/settings.png`});
await page.setViewportSize({width:1280,height:960});
await page.getByRole('button',{name:'Leoqo home',exact:true}).click();
await page.screenshot({path:`${dir}/desktop.png`});
await browser.close();
console.log(`Saved nine review screenshots to ${dir}`);
