import type {ImageSourcePropType} from 'react-native';
export const clubCrests:Record<string,ImageSourcePropType>={
"AEK Athens FC":require('../assets/crests/50129.png'),
"Aston Villa":require('../assets/crests/52683.png'),
"Atlético de Madrid":require('../assets/crests/50124.png'),
"Borussia Dortmund":require('../assets/crests/52758.png'),
"FC Barcelona":require('../assets/crests/50080.png'),
"FK Bodø/Glimt":require('../assets/crests/59333.png'),
"Club Brugge KV":require('../assets/crests/50043.png'),
"Como 1907":require('../assets/crests/79946.png'),
"Fenerbahçe SK":require('../assets/crests/52692.png'),
"Feyenoord":require('../assets/crests/52749.png'),
"LASK":require('../assets/crests/63405.png'),
"RB Leipzig":require('../assets/crests/2603790.png'),
"LOSC Lille":require('../assets/crests/75797.png'),
"Liverpool FC":require('../assets/crests/7889.png'),
"Manchester City":require('../assets/crests/52919.png'),
"Manchester United":require('../assets/crests/52682.png'),
"SSC Napoli":require('../assets/crests/50136.png'),
"Paris Saint-Germain":require('../assets/crests/52747.png'),
"FC Porto":require('../assets/crests/50064.png'),
"Real Betis Balompié":require('../assets/crests/52265.png'),
"Real Madrid C.F.":require('../assets/crests/50051.png'),
"AS Roma":require('../assets/crests/50137.png'),
"ŠK Slovan Bratislava":require('../assets/crests/52797.png'),
"Sabah FC":require('../assets/crests/2609356.png'),
"SK Slavia Praha":require('../assets/crests/52498.png'),
"Sporting Clube de Portugal":require('../assets/crests/50149.png'),
"VfB Stuttgart":require('../assets/crests/50107.png'),
"Viking FK":require('../assets/crests/52319.png'),
"Villarreal CF":require('../assets/crests/70691.png'),
"FC Bayern München":require('../assets/crests/50037.png'),
"Galatasaray A.Ş.":require('../assets/crests/50067.png'),
"PSV Eindhoven":require('../assets/crests/50062.png'),
"FC Shakhtar Donetsk":require('../assets/crests/52707.png'),
"Arsenal FC":require('../assets/crests/52280.png'),
"FC Internazionale Milano":require('../assets/crests/50138.png'),
"RC Lens":require('../assets/crests/52277.png'),
"Arsenal":require('../assets/crests/52280.png'),
"Bournemouth":require('../assets/crests/bournemouth.png'),
"Brentford":require('../assets/crests/brentford.png'),
"Brighton & Hove Albion":require('../assets/crests/brightonhovealbion.png'),
"Chelsea":require('../assets/crests/chelsea.png'),
"Coventry City":require('../assets/crests/coventrycity.png'),
"Crystal Palace":require('../assets/crests/crystalpalace.png'),
"Everton":require('../assets/crests/everton.png'),
"Fulham":require('../assets/crests/fulham.png'),
"Hull City":require('../assets/crests/hullcity.png'),
"Ipswich Town":require('../assets/crests/ipswichtown.png'),
"Leeds United":require('../assets/crests/leedsunited.png'),
"Liverpool":require('../assets/crests/7889.png'),
"Newcastle United":require('../assets/crests/newcastleunited.png'),
"Nottingham Forest":require('../assets/crests/nottinghamforest.png'),
"Sunderland":require('../assets/crests/sunderland.png'),
"Tottenham Hotspur":require('../assets/crests/tottenhamhotspur.png'),
"Alavés":require('../assets/crests/deportivoalaves.png'),
"Athletic Bilbao":require('../assets/crests/athleticbilbao.png'),
"Atlético Madrid":require('../assets/crests/atleticodemadrid.png'),
"Barcelona":require('../assets/crests/50080.png'),
"Celta Vigo":require('../assets/crests/celtadevigo.png'),
"Deportivo A Coruña":require('../assets/crests/deportivoacoruna.png'),
"Elche":require('../assets/crests/elche.png'),
"Espanyol":require('../assets/crests/rcdespanyolbarcelona.png'),
"Getafe":require('../assets/crests/getafe.png'),
"Levante":require('../assets/crests/levanteud.png'),
"Málaga":require('../assets/crests/malaga.png'),
"Osasuna":require('../assets/crests/caosasuna.png'),
"Racing Santander":require('../assets/crests/racingsantander.png'),
"Rayo Vallecano":require('../assets/crests/rayovallecano.png'),
"Real Betis":require('../assets/crests/realbetisbalompie.png'),
"Real Madrid":require('../assets/crests/50051.png'),
"Real Sociedad":require('../assets/crests/realsociedad.png'),
"Sevilla":require('../assets/crests/sevilla.png'),
"Valencia":require('../assets/crests/valencia.png'),
"Villarreal":require('../assets/crests/70691.png'),
"Atalanta":require('../assets/crests/atalantabc.png'),
"Bologna":require('../assets/crests/bologna1909.png'),
"Cagliari":require('../assets/crests/cagliaricalcio.png'),
"Como":require('../assets/crests/79946.png'),
"Fiorentina":require('../assets/crests/acffiorentina.png'),
"Frosinone":require('../assets/crests/frosinonecalcio.png'),
"Genoa":require('../assets/crests/genoacfc.png'),
"Inter Milan":require('../assets/crests/50138.png'),
"Juventus":require('../assets/crests/juventus.png'),
"Lazio":require('../assets/crests/sslazio.png'),
"Lecce":require('../assets/crests/uslecce.png'),
"AC Milan":require('../assets/crests/milan.png'),
"Monza":require('../assets/crests/monza.png'),
"Napoli":require('../assets/crests/50136.png'),
"Parma":require('../assets/crests/parmacalcio1913.png'),
"Roma":require('../assets/crests/50137.png'),
"Sassuolo":require('../assets/crests/ussassuolo.png'),
"Torino":require('../assets/crests/torino.png'),
"Udinese":require('../assets/crests/udinesecalcio.png'),
"Venezia":require('../assets/crests/venezia.png'),
"FC Augsburg":require('../assets/crests/augsburg.png'),
"Union Berlin":require('../assets/crests/1unionberlin.png'),
"Werder Bremen":require('../assets/crests/werderbremen.png'),
"SV Elversberg":require('../assets/crests/07elversberg.png'),
"Eintracht Frankfurt":require('../assets/crests/eintrachtfrankfurt.png'),
"SC Freiburg":require('../assets/crests/freiburg.png'),
"Hamburger SV":require('../assets/crests/hamburger.png'),
"TSG Hoffenheim":require('../assets/crests/tsg1899hoffenheim.png'),
"1. FC Köln":require('../assets/crests/1koln.png'),
"Bayer Leverkusen":require('../assets/crests/bayer04leverkusen.png'),
"Mainz 05":require('../assets/crests/1fsvmainz05.png'),
"Borussia Mönchengladbach":require('../assets/crests/borussiamonchengladbach.png'),
"Bayern Munich":require('../assets/crests/50037.png'),
"SC Paderborn":require('../assets/crests/paderborn07.png'),
"Schalke 04":require('../assets/crests/schalke04.png'),
};
